- content/blog/news/second-post.md
- content/blog/releases/in-depth-monoliths-detailed-spec.md
- layouts/partials/hooks/body-end.html
- layouts/partials/hooks/head-end.html
- static/admin/config.yml
- static/admin/index.html
https://www.netlifycms.org/docs/add-to-your-site/
> add everything needed for CMS

- .github/ISSUE_TEMPLATE/documentation-issue-template.md
> Update issue templates

- content/en/docs/contribution_guidelines/maintain_customize.md
- i18n/en.toml
- layouts/partials/page-meta-links.html
- Add a button to right nav to edit using netlify cms
- Update docs to describe how to do this
> RDAPI-16736: addcmsbutton

- content/en/docs/apiportal_admin/sso/sso_config.md
- content/en/docs/contribution_guidelines/writing_markdown.md
- fixed another issue with zoomin build
- added guidance on not using indentation for code blocks
> Iap 2492 fixhtml

- content/en/docs/apiportal_install/install_software_configure_database.md
adding ssl changes for 7.8 branch
> IAP-2395: SSL certs generation in the proper path.

- README.md
> update readme with basic info

- Gruntfile.js
- package.json
Added gruntfile for npm build tool w/ md linter configured w/ desired rules (task disabled)
> Added gruntfile for npm build

- content/en/docs/apiportal_install/_index.md
@aliu2 would you mind checking and approving this so I can merge as Andrea is off, it's one topic that got missed when we reformatted the json
> reformat index topic so it appears in CMS

- content/en/docs/apiportal_admin/role_mapping.md
It's not super obvious, that the mappings can't be combined and we should make that clear.
> Portal-User mapping - Make clear mappings are individual

- content/en/docs/contribution_guidelines/_index.md
@alexearnshaw can you please have a look before I ask mbice to review it? Thanks, Andrea.
> Update contribution guidelines

- content/en/docs/central/proxy_rate_limit.md
Trying to get the intro to bridge and flow into the second paragraph a little better.
> bridging_update

- content/en/docs/apimgr_admin/sso/sso_mapping.md
- Add the userfullname optional attribute
- Improve format of attributes listing
Relates to Jira https://techweb.axway.com/jira/browse/RDAPI-17803
> add userfullname attribute and improve format of attributes list

- content/en/docs/contribution_guidelines/_index.md
- content/en/docs/contribution_guidelines/deleting_a_repository.md
Update the procedure on how to delete the fork, and the contributions guidelines because this is the first thing users will read, so I think it's important to add information there in the first place. 
Fixes #149
> Updates regard to deleting a fork

- content/en/docs/contribution_guidelines/_index.md
- content/en/docs/contribution_guidelines/deleting_a_repository.md
- content/en/docs/contribution_guidelines/maintain_customize.md
- content/en/docs/contribution_guidelines/setup_work_locally.md
fixes #161 
@andreamussap can you review please?
> update contrib topics for maintainers

- content/en/docs/apigtw_ref/general_settings.md
- content/en/docs/apigw_poldev/gw_instances/general_remote_hosts.md
- content/en/docs/apimgr_ref/api_mgmt_config_web.md
Update Active timeout settings and fix formatting/display of the parameters.
> RDAPI-18183 Update Active timeout settings

- content/en/docs/apiportal_admin/apip_overview.md
@teivanov  I tweaked the paragraph about Applications. Can you please review that this is technically accurate? Thanks!
(Triggered by https://techweb.axway.com/jira/browse/IAP-2006)
> update Creating and managing applications

- content/en/docs/cass_admin/cassandra_bur.md
Reverts Axway/axway-open-docs#188
> Revert Update Apache Cassandra administration cassandra_bur

- content/en/docs/apim_administration/apimgr_admin/sso/saml_sso_config.md
Video showing all steps required to configured SSO based on they Keycloak example. 
I added this video at the top to make sure everybody sees it, before stepping into the details..
> Video demonstraing how to configure SSO using Keycloak

- .github/ISSUE_TEMPLATE/website-issue-template.md
Realized that small type while creating a new issue.
> Fixed typo: WEDSITE to WEBSITE

- content/en/docs/apim_relnotes/apimng_releasenotes/_index.md
Additional Comments for the release notes
> Update API Gtw and Mng Release Notes

- content/en/docs/cass_admin/cassandra_config.md
Improvements to style and voice of the additions made in PR #122 (which have been merged via CLI)
> TW review of Cassandra param additions

- content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
> Review PR 224 Minor updates

- .github/stale.yml
@alexearnshaw this is to try to find out why the stale app didn't work
Double checking the procedure:
1. - Instructions at https://github.com/probot/stale
2. - Create a .github/stale.yml in the default branch, based on a given template
- I've opened the file in VSCode and couldn't (manually) see any issues with the YAML format!?
- I've double checked that the relevant parameters are enabled.
- I've added issue #245 to Axway board (I don't think this should be an issue but it's easier to follow the issue anyways)
Although I don't think this is the reason why the Stale app didn't work, I've commented out this line just to make sure:
```
Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels: []
```
Please approve this and lets follow …
> Update stale yaml file

- content/en/docs/central/catalog/catalog_integrationbuilder.md
Updated catalog_integrationbuilder.md with an authentication section that includes a video
> APIGOV-12818 authentication video

- .github/stale.yml
Update #days for `daysUntilStale` and `daysUntilClose` parameters.
> Stale tickets - update number of days

- .github/CODEOWNERS
- Added POs for all docs
- Added missing poldev directory
- Updated release notes dir as file names have changed and apig and apim RN were merged
> Update codeowners with POs

- content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
* Change link for API docs
* Remove unnecessary sentance
> Update release notes:

- content/en/docs/apim_installation/apigtw_install/cassandra_install.md
- content/en/docs/apim_installation/apigtw_install/install_dev_tools.md
- content/en/docs/apim_installation/apigtw_install/installation_unattended.md
- content/en/docs/apim_installation/apigtw_install/system_requirements.md
- content/en/docs/apim_installation/apigw_containers/container_patch_sp.md
Improves #354 and other pages.
> Readability improvements

- content/en/docs/apim_installation/apigw_containers/configure_edge_agent.md
- content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
- content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
> RDAPI-18936 subscription agent

- content/en/docs/apim_installation/apigw_containers/configure_edge_agent.md
@alexearnshaw please approve this. It's just a detail that I missed before. Thanks
> Configure usage tracking - adding more information

- content/en/docs/contribution_guidelines/setup_work_locally.md
The idea here is to update the doc with fully detailed steps so that a tech writer (or anyone else with limited tech knowledge) can install the tools and build the site locally.
Subsequent PRs will address more use cases.
> RDAPI-16771: Update maintainer docs with more detail on installation

- layouts/partials/hooks/head-end.html
Add the hotjar tracking code to all pages via layout template
fixes #146
> Add hotjar code

- content/en/docs/central/cli_proxy_flow.md
Adding information on new properties of the oauth clientAuth
> [APIGOV-11528] Update cli_proxy_flow.md

- content/en/docs/central/quickstart.md
This PR is to replace and existing obsolete video with a new video that demonstrates the new features that are available.
> Update "Register an API" video in "Get started with AMPLIFY Central" page

- content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200330_apimgr_relnotes/fixed_issues.md
- content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
- content/en/docs/apim_relnotes/20200330_apip_relnotes/fixed_issues.md
- static/admin/config.js
* Create new files for APIG/M and APIP
* Remove FIPS steps from APIG/M
* Add new RN to CMS
* Add note indicating they're still being updated
> Add Mar20 release notes:

- package-lock.json
- package.json
Updated npm package minimist to fix security vulnerability
> Update minimist dependency

- content/en/docs/apim_installation/apigw_containers/container_getstarted.md
Adds a link to helm charts for K8S
Fixes #318 
> Add FAQ for Kubernetes with link to Helm charts

- content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
- content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Update Release Notes title to remove the complete date (eg. 7.7.20200130) and leave just Month/Year (eg. 7.7 Mar20) because this reads well.
> Update Release Notes title

- content/en/docs/apim_administration/apigtw_admin/admin_fips.md
- content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
* Add info about OpenSSL and FIPS in Mar20 RN
* Add note about FIPS support to main FIPS topic
* Remove continuous updates notes from both RNs
> RDAPI-19315 FIPS update

- content/en/docs/shared_services/supportapi/_index.md
@alexearnshaw I've removed the link from linktitle otherwise the link won't render on the webpage. Then I've added it to the body of the content. Feel free to change it more if you like.
> [Shared Services] Remove link from linkTitle and add it to the body

- content/en/docs/_index.md
- Add info to doc start page about what open docs is
- Reduce the length of the page title (especially on Zoomin where the title appears in the left navigation menu) by taking the product names out of the page title and instead having them them in the page content.
- Explain to users how they can navigate/search and give them some starting points for each product
- Remove the auto-generated list of topics with no_list:true
Fixes #385  …
> Improve the start page

- content/en/docs/apim_policydev/apigw_polref/integrity_xml.md
Added a small section about missing document about Include Transforms option in the XML Sign Filter.
* [ x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ x ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ x ] You have verified the technical accuracy of your change
* [ x ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
_This section is to …
> [RDAPI-18860] XML Sign filter has undocumented "Include Transforms" option

- content/en/docs/apim_administration/apiportal_admin/public_api_configure.md
> Cms/ygeorgiev axway/axway open docs/apiportal admin/public api configure

- content/en/docs/apigtw_devguide/jmx_enable.md
Fix list of steps in the procedure.
@alexearnshaw I'm adding screenshot here because when I fixed the list in the MD file, VS Code didn't recognize this as a change so there was nothing for me to save the fix. So I had to change some minor thing in the text so it would pick up the change and let me update/save this file.
> Enable API Gateway with JMX Fix ordered list of steps

- content/en/docs/contribution_guidelines/setup_work_locally.md
Added procedures for updating the Ubuntu bash prompt, and setting up symlinks to work with Windows files.
> Add some tips for working on Ubuntu

- content/en/docs/apim_relnotes/201904_apip_relnotes/_index.md
change the order of 2019 RN to last - @andreamussap I couldn't do this as part of the other PR so here's a new one for it, can you approve pls?
> change the order of 2019 RN to last

- content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
- content/en/docs/apim_installation/apigtw_install/system_requirements.md
The MariaDB database is not natively supported as the vendor name (mariadb used in the JDBC-Connect string) is not mapped internally into the driver class-name. As a result, customers get the following error message:
No JDBC Driver found for the name: mariadb
And we only support the MySQL-JDBC drivers up to the version 5.1.x. Versions: 6.x.x & 8.x.x are not supported leading to a ClassNotFoundException. This is due to the fact, that the internal package structure has changed from:
`org.gjt.mm.mysql.Driver`
to
`com.mysql.jdbc.Driver`
We we map the vendor name: mysql in the connect string to: org.gjt.mm.mysql.Driver
Of course, it would be time to improve our mapping, as the new package name has been introduced in Mar/2016, but we haven't done it yet. That is another story.
@maherb4, …
> MariaDB is only supported by the MySQL-Driver.

- .markdownlint.json
When users edit a page via Netlify CMS, Netlify removes the single/empty line at the end of the page, and this triggers the markdownlinter error MD047.
**Resolution**: disable [MD047 - Files should end with a single newline character](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md047---files-should-end-with-a-single-newline-character) rule in axway-open-docs project.
_This section is to be filled out by project …
> Disable MD047 markdown rule

- content/en/docs/apim_installation/apiportal_install/connect_to_apimgr.md
Actually the API-Portal setup is a bit disconnected from the API-Manager. And customers/partners, etc. don't realize immediately, that the API-Portal depends on the API-Manager. They always asking me: What is default user to login into the API-Portal?
Therefore, it makes sense to add some kind of the next logical step, when the API-Portal has been connected to the API-Manager: Very likely they would like to login.
_This section is to be …
> Added information how to login

- config.toml
- content/en/docs/contribution_guidelines/maintain_customize.md
- content/en/docs/contribution_guidelines/setup_work_locally.md
- netlify.toml
* Upgrade Hugo locally to 0.66.0
* Set Blackfriday as default parser and turn on the extra options:
```
nofollowLinks = true 
noreferrerLinks = true 
noopenerLinks = true 
```
* Set Hugo version in Netlify config to 0.66.0
Fixes #481 
> Update Hugo version to avail of new Blackfriday options

- content/en/docs/contribution_guidelines/bestpracticedevdoc.md
@alexearnshaw  please review - Adding note to clarify to content owners worried about things getting smashed or lost in a long menu that pages usually are found by (Google) search.
> Add note on how users first land on a page

- content/en/docs/apim_administration/apigtw_admin/general_passphrase.md
> Update property as its new value is now pvalue.

- static/admin/config.js
Add AMPLIFY Unified Catalog collection to Netlify CMS, so that it's possible to edit its topics.
Fixes #513 
> Add AMPLIFY Unified Catalog to CMS

- content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
Give some context what an organization is and why people should create them instead of only telling how to setup an organization, which is an easy task anyway.
> What is an Organization

- content/en/docs/apim_relnotes/201904_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
- content/en/docs/apim_relnotes/20200530_apimgr_relnotes/_index.md
- content/en/docs/apim_relnotes/20200530_apimgr_relnotes/fixed_issues.md
- content/en/docs/apim_relnotes/20200530_apip_relnotes/_index.md
- content/en/docs/apim_relnotes/20200530_apip_relnotes/fixed_issues.md
- static/admin/config.js
> Add release notes for May2020

- content/en/docs/central/fundamental_concepts.md
Added the AMPLIFY Central roles
> Added the AMPLIFY Central roles

- static/admin/config.js
> Add Connect API Manager and AWS Gateway collections

- content/en/docs/central/connect-aws-gateway/_index.md
Fixed one typo and changed to external links to point to new location.
* [x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x ] You have signed the [Axway CLA](https://cla.axway.com/)
* [x ] You have verified the technical accuracy of your change
* [x ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
> cleanup external links

- static/admin/config.js
I forgot to add the full path to the subfolders in the new APIM overview, this fixes that so the subfolder topics also work in CMS.
> Add full path to concepts and components collections

- content/en/docs/apim_administration/apimgr_admin/api_mgmt_alerts.md
- Removed alerts: API Deleted & API Proxy Authentication Policy Change as they don't exists.
- Added alert: API Proxy Unpublished
- Added an important detail, that the API Published Alert is also triggered for a publication request
- As the list of attributes is incomplete anyway (actually only Application credential alerts are listed in the table) I added a recommendation to use a Trace-Filter to discover attributes.
Fixed some issues and enhanced the content.
_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
> API-Management Alerts - Fixes and enhancements

- .github/ISSUE_TEMPLATE/documentation-issue-template.md
- .github/ISSUE_TEMPLATE/website-issue-template.md
- .github/pull_request_template.md
This adds a new check for contribs and maintainers regarding exposure of sensitive info
> Add new checks for sensitive info, fix lint errors

- content/en/docs/apim_administration/apimgr_admin/api_mgmt_alerts.md
This replaces PRs #702 and #697 
> Replace video with official version from Axway YT

- content/en/docs/apim_relnotes/20200530_apimgr_relnotes/_index.md
Updated the Policy Studio and Configuration Studio service pack update steps for May2020 One Version release.
Changed the service pack update steps to show the new script that will be used in May 2020 release.
> PolicyStudio/ConfigStudio SP steps - May2020

- content/en/docs/api_mgmt_overview/api_mgmt_components/pipeline.md
Fixing link to the correct Maven Plugin for API Gateway Policy Development project on our GitHub-Repository. I previously linked the wrong one.
> Fixing link to the correct GitHub-Project

- layouts/partials/page-meta-links.html
Update the link to create a Github issue to use the documentation issue template. Relates to PR #724 
> Use the issue template when creating issues from website

- content/en/docs/contribution_guidelines/_index.md
Fixes #700 
Add more information about using this option when you want to contribute but don't have the knowledge to do so. Add information about what happens when you submit an issue, e.g. what happens next depending on if it's a simple fix or if it needs R&D, prod mgmt involved.
> Update contrib guidelines for creating Github issues

- content/en/docs/apim_administration/apigtw_admin/tracing.md
Reverts Axway/axway-open-docs#733 
Ryan asked to revert this as his dev changes aren't in master yet and he needs to add more changes.
> Revert "Update page in APIG admin section “tracing”"

- content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
Reverts Axway/axway-open-docs#732
Ryan asked to revert this as his dev changes aren't in master yet and he needs to add more changes.
> Revert "Update page in APIM SSO section “c_saml_trouble”"

- content/en/docs/apimgmt_security/c_secgd_bp_intro.md
Reference https://jira.axway.com/browse/RDAPI-18387
- Changes made accordingly with email and file attached to the Jira.
- On section 'Sensitive files and databases' there's a note to add a new paragraph to comply with Swift requirements, but I don't know if this applies here.
> RDAPI-18387 Update Security Guide Best practices

- netlify.toml
This makes the Edit on CMS link point to the correct URL in the develop site
> Use DEPLOY_PRIME_URL in build command for develop

- content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_token_info.md
Request to the tokeninfo service now uses HTTP POST. GET is no longer allowable as it may show the access_token in the URL.
> RDAPI-20086. Token Information Endpoint API.

- content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
- content/en/docs/apim_relnotes/20200730_apip_relnotes.md
Add July RNs for APIP and APIG/M to the develop branch. Improve consistency. Also fixes #280 
> Template for July RNs, improve consistency

- package-lock.json
Fixes the warning "Browserslist: caniuse-lite is outdated" that appears when you run hugo server as per https://github.com/postcss/autoprefixer/issues/1184. In short this involved running a command which updated the package-lock.json file. 
I also tried to fix the "Replace Autoprefixer browsers option to Browserslist config." issue that also appears when running hugo server but it turns out this is something that needs to be fixed in Docsy (https://github.com/google/docsy/issues/120) …
> Fix Caniuse issue when running hugo

- content/en/docs/central/fundamental_concepts.md
Previous link was dead, updating link to Organization Management page.
I fixed a dead link and corrected it to the resource it was intending to link to.
> Fixing dead link

- content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
- content/en/docs/central/connect-api-manager/deploy-your-agents.md
- content/en/docs/central/connect-api-manager/discovery-agent-flags.md
- content/en/docs/central/connect-api-manager/discovery-agent-variables.md
- content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
- content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
- content/en/docs/central/connect-api-manager/prepare-amplify-central.md
- content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
- content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
- content/en/docs/central/connect-aws-gateway/_index.md
- content/en/docs/central/connect-aws-gateway/agent-security-aws.md
- content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
- content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
- content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
- content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
- content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
- content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
> removed Alpha note from all topics

- content/en/docs/central/quickstart.md
Currently we are able to show maximum of 1000 transactions on API Traffic page due to some constraints on the backend.
> Add a note on the limit on API Traffic page

- content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
> APIGOV-15414 - Add AWS cost

- content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
- content/en/docs/central/connect-aws-gateway/agent-security-aws.md
Adding content for securing the credentials
> APIGOV-15313 - securing credentials

- content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Changes requested for https://jira.axway.com/browse/RDAPI-20252 to include reference to Client App Registry throughout the Run 'update-apimanager' step.
> [RDAPI-20252] SP13 Installation questions with respect to Client App Registry only install

- content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
[RDAPI-20570] Policy Studio May update on Windows - requires clarification on the Policy Studio / Configuration Studio update steps
> [RDAPI-20570] Policy Studio May update on Windows for JULY20 release

- content/en/docs/central/mesh_management/add_env.md
Added new helm install command for apic-hybrid chart installation to incorporate als-traceability-agent (ObserverV2) deployment with mesh set up instructions.
> Updated  helm install command for ALS deployment

- content/en/docs/apim_policydev/apigw_poldev/general_messaging.md
This PR changes the link to "Embedded ActiveMQ settings" page where the serialization restrictions are described.
> Fix the link to Embedded ActiveMQ settings page

- content/en/docs/apim_administration/apimgr_sso/_index.md
In order to utilize the ability of a user being a member of multiple organizations in api manager the 1.4 version of the api must be used at the sso login step.
> RDAPI-21491 Use API 1.4 version to be able to add user as member of multiple organizations.

- content/en/docs/apim_administration/apimgr_sso/saml_sso_config.md
Update to show how you configure the v1.4 servlet for sso which can enable a user to be a member of multiple orgs.
> RDAPI-21491 - Add instructions to use API and servet v1.4 to enable multiple organizations

- content/en/docs/apim_administration/apimgr_sso/sso_mapping.md
RDAPI-21491 Updating to show usage of the orgs2Role attribute to enable a user having membership of multiple API Manager organizations.
> RDAPI-21491 New section 'orgs2Role' attribute to enable multiple organizations

- content/en/docs/apim_administration/apimgr_admin/api_mgmt_monitor.md
> RDAPI-21234 Added information about Date interval behaviour for API Manager metrics

- content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
> Update New features and enhancements on May 20 Release Notes

- content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Release note changes because of https://jira.axway.com/browse/RDAPI-20896 [CWE-327] Broken & Risky Algorithms in Apache SSHd configuration
> RDAPI-20896 Update 20200930_apimgr_relnotes.md

- content/en/docs/apim_administration/apimgr_sso/saml_sso_config.md
…ter sso saml response verification.
> RDAPI-21683 Configure orgs2Role header using a policy to assign user to multi organizations

- content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
> RDAPI-15950 Update steps to create user with multi organizations

- content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
> [RDAPI-21825] - Small updates to sept 2020 release notes for multiorg

- content/en/docs/apim-reference-architectures/container-aws/_index.md
- content/en/docs/apim-reference-architectures/container-azure/_index.md
Align the common elements of the reference architectures across the AWS and Azure documents
> Synchronize AWS and Azure ref arch common content

- content/en/docs/cass_admin/cassandra_bur.md
> RDAPI-21027 Cassandra re-index script changes

- content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Updated to specify Groovy jars have been updated from version 2.4.8.
Added RDAPI-21984 to list of known issues as this causes the "Date.format()" function to not work.
> RDAPI-21984 Update 20200930_apimgr_relnotes.md

- content/en/docs/apim_administration/apigtw_admin/general_certificates.md
> Merge by andrea

- content/en/docs/apim_installation/apigtw_install/system_requirements.md
It is confusing, to state: 
This section is for Developer-Tools only and not for the API-Gateway, but then in the next section we say: API-Gateway supports ....
Changed this to Developer tools supports ....
Also changed one of titles that was using `code` formatting and looked ugly.
Before merging this PR, please …
> Windows section - Developer tools instead of API-Gateway

- package-lock.json
- package.json
See discussion on https://jira.axway.com/browse/RDAPI-22318
> RDAPI-22318 Update package-lock.json to fix yargs-parser security vulnerability

- content/en/docs/apim_installation/apigw_upgrade/upgrade_analytics.md
> [RDAPI-21986] Update Docs with steps to migrate Analytics data

- content/en/docs/apim_installation/apiportal_docker/Upgrade_docker.md
- content/en/docs/apim_installation/apiportal_docker/docker_config.md
- content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
Related to https://github.com/Axway/axway-open-docs/pull/1429
**Task**: Add {"draft": "true"} to the frontmatter of the following pages to temporarily hide them:
- Upgrade API Portal docker deployment (content/en/docs/apim_installation/apiportal_docker/Upgrade_docker.md)
- Customize API Portal topology in Docker (content/en/docs/apim_installation/apiportal_docker/docker_config.md)
- Build and run API Portal using Dockerfile (content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md)
@dginevaAxway @jowens-axway FYI.
_Put an x in the boxes that apply. If you're …
> IAP-3685: temporarily hide pages for the upcoming release

- content/en/docs/apim_installation/apiportal_docker/_index.md
- content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
https://deploy-preview-1454--axway-open-docs.netlify.app/docs/apim_installation/apiportal_docker/docker_portal_run_image/
* change required components section
* change non-root container section
Before merging …
> IAP-3685: more updates to Run API Portal using Docker image

- content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
Updating the upgrade and update section to point to the main page in the release notes as part of RDAPI-22303
> RDAPI-22303 Update 20201130_apimgr_relnotes.md

- .github/workflows/ciworkflow.yml
- .github/workflows/merge_to_develop.yml
- layouts/partials/page-meta-links.html
- netlify.toml
- static/admin/config.js
For more information, see https://jira.axway.com/browse/RMF-72
> RMF-72 Configure Jan21 develop branch for API Management release

- netlify.toml
Complements #1475 
For more information, see https://jira.axway.com/browse/RMF-72
> Update context tag

- .github/workflows/ciworkflow.yml
- .github/workflows/merge_to_develop.yml
- layouts/partials/page-meta-links.html
- netlify.toml
- static/admin/config.js
For more information, see https://jira.axway.com/browse/RMF-72
> RMF-72 Configure Jan21 develop branch - continue

- .github/pull_request_template.md
Fixes https://jira.axway.com/browse/RMF-74
> RMF-74 Update pull request template

- content/en/docs/central/mesh_management/build_hybrid_env.md
Updated the supported version of Kubernetes for hybrid clusters.
> Update supported k8s version for hybrid

- content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
https://deploy-preview-1535--axway-open-docs.netlify.app/docs/apim_policydev/apigw_gw_instances/general_services/
> RDAPI-20442 Disable SSL renegotiation on TLS 1.2 Listeners and lower

- content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
https://deploy-preview-1534--axway-open-docs.netlify.app/docs/apim_relnotes/20210130_apimgr_relnotes/#new-features-and-enhancements
Complementary PRs:
#1538 
#1539 
> RDAPI-20442 Disable SSL renegotiation on TLS 1.2 Listeners and lower: Update page in APIM release note section “20210130_apimgr_relnotes”

- content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
https://deploy-preview-1539--axway-open-docs.netlify.app/docs/apim_policydev/apigw_gw_instances/general_services/
> Update page in instances and listeners section “general_services”

- content/en/docs/apim_administration/apigtw_admin/general_certificates.md
https://deploy-preview-1542--axway-open-docs.netlify.app/docs/apim_administration/apigtw_admin/general_certificates/
Adding OpenSSL 1.0 incompatibility warnings to both OpenSSL engines and HSM sections.
> [RDAPI-22362] Update page in APIG admin section “general_certificates”

- content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Add JOSE Header setting to JWT Sign Filter
https://deploy-preview-1562--axway-open-docs.netlify.app/docs/apim_policydev/apigw_polref/integrity_additional/
> [RDAPI-22658] Add JOSE Header setting to JWT Sign Filter

- content/en/docs/apim_administration/apiportal_admin/apip_overview.md
Preview: https://deploy-preview-1576--axway-open-docs.netlify.app/docs/apim_administration/apiportal_admin/apip_overview/
> IAP-3867: Add information about new SwaggerUI layout

- content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
- content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
- content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
See preview links
https://deploy-preview-1583--axway-open-docs.netlify.app/docs/apim_relnotes/20201130_apimgr_relnotes/
https://deploy-preview-1583--axway-open-docs.netlify.app/docs/apim_relnotes/20210130_apimgr_relnotes/
> [RDAPI-23050] Add release notes for YAML for Nov and Jan21.

- content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
https://deploy-preview-1585--axway-open-docs.netlify.app/docs/apim_relnotes/20210130_apimgr_relnotes/#deprecated-features
> Update API Gateway Jan21 Deprecated features

- content/en/docs/central/cli_central/cli_apiservices.md
- content/en/docs/central/cli_central/cli_command_reference.md
- content/en/docs/central/cli_central/cli_create_fetch_resources.md
https://deploy-preview-1546--axway-open-docs.netlify.app/docs/central/cli_central/cli_apiservices/
https://deploy-preview-1546--axway-open-docs.netlify.app/docs/central/cli_central/cli_command_reference
https://deploy-preview-1546--axway-open-docs.netlify.app//docs/central/cli_central/cli_create_fetch_resources
-Added a CLI command reference page that will serve as an 'index' for CLI users
-Updated the docs page centered around APIServices and the CLI with sample output
-Added a CLI create/fetch resource page with examples and links to sample resource files the user can use
_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to …
> Add CLI command reference docs page; update API Services docs page; add create/fetch docs page with more sample files and examples

- content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
https://deploy-preview-1590--axway-open-docs.netlify.app/docs/apim_relnotes/20210130_apimgr_relnotes/#content-security-policy-header-to-improve-security
> Update page in APIM release note section “20210130_apimgr_relnotes”

- content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
- content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
- content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
- content/en/docs/central/connect-azure-gateway/network-traffic-azure.md
Adding the static IP address
Creating the network page for Azure agents
> Apigov 17530 - add static IP address

- content/en/docs/central/mesh_management/deploy-your-agents-with-the-amplify-cli.md
- content/en/docs/central/mesh_management/discover-apis-and-services.md
Updated CLI install steps for the Kubernetes agent to reflect the change from asking for a K8SCluster, to asking for an Environment.
Updated description of the resources used by the Kubernetes discovery agents to reflect the new resources added.
> APIGOV-17201 Update CLI Kubernetes install steps, and resources used by the Kubernetes discovery agent

- content/en/docs/apim_installation/apiportal_install/install_unattended.md
> IAP-3508 Add options file documentation

- content/en/docs/apim_installation/apigtw_install/verify_downloads.md
https://deploy-preview-1677--axway-open-docs.netlify.app/docs/apim_installation/apigtw_install/verify_downloads
> [RDAPI-19415] Add PGP Verification page

- content/en/docs/apim_installation/apigtw_install/cassandra_install.md
https://deploy-preview-1674--axway-open-docs.netlify.app/docs/apim_installation/apigtw_install/cassandra_install/#cassandra-hardware
> RDAPI-16778 Add recommendations for Cassandra storage

- content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Update advice on privileged ports and relocate advice to back up customized files.
https://deploy-preview-1678--axway-open-docs.netlify.app/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion/
> Update 'API Gateway One Version' to add instruction on privileged ports

- content/en/docs/apim_installation/apigw_upgrade/upgrade_faq.md
New section - **How to increase timeouts for apply**.
https://deploy-preview-1679--axway-open-docs.netlify.app/docs/apim_installation/apigw_upgrade/upgrade_faq/#how-to-increase-timeouts-for-apply
> Add steps to run sysupgrade apply with increased timeouts

- content/en/docs/apim_reference/managedomain_ref.md
- content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
- content/en/docs/apim_yamles/yamles_packaging_deployment.md
The PR aims to provide information on how to create an api gateway instance deployed with a YAML factory
https://deploy-preview-1701--axway-open-docs.netlify.app/docs/apim_reference/managedomain_ref
https://deploy-preview-1701--axway-open-docs.netlify.app/docs/apim_yamles/yamles_packaging_deployment
https://deploy-preview-1701--axway-open-docs.netlify.app/docs/apim_yamles/apim_yamles_references/yamles_known_limitations
> RDAPI-20494 Creation of new apigateway with yaml factory option

- content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> [RDAPI-22182] HSTS Release Note

- content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
JWT Verify Filter Update
https://deploy-preview-1753--axway-open-docs.netlify.app/docs/apim_policydev/apigw_polref/integrity_additional
> [RDAPI-23614] JWT Verify Filter update

- content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Make change to release note YAML ES 
https://deploy-preview-1760--axway-open-docs.netlify.app/docs/apim_relnotes/20210330_apimgr_relnotes/
> Update Yaml ES in release note

- content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Added a release note on newly discovered Policy Studio bug, PS can't upgrade some feds, release note includes a workaround
https://deploy-preview-1786--axway-open-docs.netlify.app/docs/apim_relnotes/20210330_apimgr_relnotes/
> RDAPI-23876 Update Know Issues on March 21 release - PS Can't upgrade NM or Analytics projects or feds

- content/en/docs/central/mesh_management/add_env.md
- content/en/docs/central/mesh_management/build_hybrid_env.md
- content/en/docs/central/mesh_management/deploy-your-agents-with-the-axway-cli.md
- content/en/docs/central/mesh_management/discover-apis-and-services.md
- content/en/docs/central/mesh_management/traceability_agent_configuration.md
> Ampc-hybrid changes to helm commands

- content/en/docs/central/mesh_management/deploy-your-agents-with-the-axway-cli.md
- content/en/docs/central/mesh_management/discover-apis-and-services.md
- content/en/docs/central/mesh_management/traceability_agent_configuration.md
> Upgrading CLI version to 1.7.0

- content/en/docs/apim_installation/apiportal_install/install_unattended.md
* add mysql-keep option to unattended install page
* fix shell code demo type
> IAP-4062 Update Install Unattended with mysql-keep option

- content/en/docs/central/connected_agent_common_reference/_index.md
- content/en/docs/central/connected_agent_common_reference/secure_config.md
Updated documentation for securing credential based agent configuration using reference for secret resource in Central
> APIGOV-18029 - Updated common reference

- content/en/docs/apim_reference/allReleasesChangeLog.md
https://deploy-preview-1936--axway-open-docs.netlify.app/docs/apim_reference/allreleaseschangelog/
> Update page in APIM ref section “allReleasesChangeLog”

- content/en/docs/apim_policydev/apigw_polref/content_max_messages.md
Add requirements to the throttling filter based on https://jira.axway.com/browse/RDAPI-24970
https://deploy-preview-2056--axway-open-docs.netlify.app/docs/apim_policydev/apigw_polref/content_max_messages/
> RDAPI-24970 Filter requirements

- content/en/docs/apim_installation/apiportal_install/install_software.md
Adding info for command change 
https://deploy-preview-2092--axway-open-docs.netlify.app/docs/apim_installation/apiportal_install/install_software/
> Update steps on Install API Portal software section

- content/en/docs/central/cli_central/cli_install.md
Updated client ids in examples to be placeholder text so users don't try to actually run the command.
JIRA: https://jira.axway.com/browse/APIGOV-20171
> Updated client ids in examples

- content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
Adding Details in the Release Notes regarding to Team Gonzo's work 
https://deploy-preview-2161--axway-open-docs.netlify.app/docs/apim_relnotes/20211130_apimgr_relnotes/#client-credentials-can-now-be-set-as-a-grant-type
> [RDAPI-25893] - Nov 21 release Update features and enhancements

- content/en/docs/apim_administration/apigtw_admin/admin_fips.md
Manually cherry-pick #2302 from master to developmay22
> Manually merge master into develop - 20220425

- content/en/docs/apim_administration/apimgr_admin/api_mgmt_config_ps.md
- content/en/docs/apim_administration/apimgr_admin/api_mgmt_consume.md
- content/en/docs/apim_administration/apimgr_admin/api_mgmt_promote.md
- content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
- content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
- content/en/docs/apim_administration/apimgr_admin/api_mgmt_workflow.md
- content/en/docs/apim_administration/apimgr_admin/example_oauth_external.md
Updates to the 'Administer API Manager' guide
http://pr-2756.axway-open-docs.opendocs-builder.pcloud.axway.int/docs/apim_administration/apimgr_admin/api_mgmt_register_web/
> RDAPI-30769 Updates for GraphQL APIs
