config.toml
content/en/_index.html
content/en/docs/contribution_guidelines/setup_work_locally.md
static/admin/config.yml

- Global search and replace all instances of the Github repo with the new repo name under the Axway org in all config and other files
- This involves no changes to content except for any links to the repo that are generated by Hugo/Netlify from the config files

rename repo links to Axway org

---

content/en/docs/apiportal_admin/_index.md
content/en/docs/apiportal_admin/customize_css_styles.md
content/en/docs/apiportal_admin/customize_getting_started.md
content/en/docs/apiportal_admin/customize_page_content.md
content/en/docs/apiportal_admin/localize_language.md
content/en/docs/apiportal_admin/troubleshooting.md
content/en/docs/cass_admin/cassandra_config.md
content/en/docs/cass_admin/cassandra_manage.md
content/en/docs/central/add_hybrid_env.md
content/en/docs/contribution_guidelines/writing_markdown.md

- Did a full sanity check and fix of the topic from the zoomin error (removed div tags, various other issues with <, >, / chars.
- Removed or added backticks to any <, >, or \ characters as these are likely to be the cause of zoomin issue as they understood as HTML in some cases and marked red in VSCode.
- Updated the writing markdown topic with tips for code blocks and a warning re using these chars

IAP-2492: remove or backtick lt, gt, and backslash chars for zoomin

---

config.toml
content/en/search.md
layouts/partials/hooks/body-end.html
layouts/partials/hooks/head-end.html
layouts/partials/search-input.html

Added the javascript code provided from Algolia DocSearch and got search working in the top nav. The search can be tested on the deploy preview but note that all the search results go to production.
Detailed changes:
- Added the javascript to head end and body end of every page by using the instructions from Docsy https://www.docsy.dev/docs/adding-content/lookandfeel/#add-code-to-head-or-before-body-end
- Create a new search-input.html file in our project - this overrides the same file in the Docsy theme and changes it to use the Algolia search instead of the GCSE
- Added a new param to config.toml for Algolia search so it can be turned on or off easily
- Set the side nav search box to false in config.toml as I couldn't get this search box working with Algolia and anyway I think one …

add JS for docsearch and enable search in config

---

.markdownlint.json

This config file for markdown lint applies the same rules to vscode as what will be used by grunt in the netlify build (when we enable it)

add same lint rules to vscode as for grunt

---

content/en/docs/apiportal_admin/role_mapping.md

I believe we should provide a link to the official Joomla-Documentation instead of letting our customers search for the right place.

Added a link to the Joomla-ACL-Doc

---

content/en/docs/apigtw_releasenotes/_index.md
content/en/docs/apimng_releasenotes/_index.md
content/en/docs/cass_admin/_index.md

This was just to move APIGTW/MNG release notes right above the Cassandra Admin in the menu.

RDAPI_17369: organize menu items order.

---

content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md

The order of arguments for the docker run command is wrong: the image name/tag should be the last argument.

Anartovich patch 1

---

content/en/docs/apim_administration/apimgr_admin/api_mgmt_promote.md

Swagger-Promote is a great way to automate the API-Manager. It's already successfully used by a lot customers and so we should make it part of the documentation, so that all customer know about it.
@maherb4, perhaps you can confirm if this is okay for you.

Added swagger promote link

---

.github/stale.yml

I've installed [Stale](https://github.com/apps/stale) - a GitHub Integration built with Probot that closes abandoned issues after a period of inactivity. After installing the integration, you must create .github/stale.yml in the default branch to enable it.

Create stale.yml to automatically close stale PR and issues

---

config.toml
netlify.toml

- Change the build command in netlify.toml to use the Netlify env variable $DEPLOY_PRIME_URL for deploy previews (as suggested in https://discourse.gohugo.io/t/correct-baseurl-on-netlify-previews/10429)
- Tested that the links in the page body work correctly on deploy previews
- Tested that the links to CMS and Contrib guidelines in right nav work correctly on deploy preview
- Tested that the links in left nav and cross-refs in the page body continue to work as before
(A future improvement would be to change the code that's used to build the CMS button and contrib guidelines link in right nav as it's not best practice from what I've read. I'll open a new issue for this.)
fixes #214

Fix the issue with links on page going to master instead of preview branch

---

.github/CODEOWNERS

Adding this file automates adding reviewers to all new pull requests. Whoever is assigned to the files or directories where the files are in the codeowners file is automatically requested as a reviewer.
At the moment it assigns:
- both tech writers as default owners for all files (both of us will be requested as reviewers if there is not a more specific rule)
- 1 tech writer to each area of doc. A review from this writer is mandatory and the PR cannot be merged without it.
- 1 SME (Mark) to the AMPLIFY Central doc (as a test). In the future we can extend this to include one or more SMEs (PO/PM or developer) to every area of doc. The SME review is not mandatory it's just a heads up for them to know the doc is changing and review if they want to.
Proposed change to the way of working:
- A …

Add a simple codeowners file

---

.github/stale.yml

Relates to #268 
Tests #245 
@alexearnshaw  I've noticed that the indentation of one parameter was wrong so I fixed it, then tested the yml file at http://www.yamllint.com/ to validate the file.

Fix parameter 'closeComment' indentation in stale.yml file

---

content/en/docs/apim_policydev/apigw_polref/attributes_manipulate.md

To create a SAML-Assertion, only the filters we provide in the section Attributes can be used, but this is sometimes not flexible enough. 
For instance, when a User has been authenticated using an OAuth-Token, a new SAML-Assertion should be created on the fly. This is a quite complicated task for a very common scenario and we should help our customers by providing an example for it. 
BTW: My plan is to add more examples into the same GitHub repository and when appropriate link it into our documentation. I hope that is okay. I would like to share knowledge and avoid everybody is creating it's own implementation. Another example I'll tackle is this one: 
https://community.axway.com/s/question/0D52X00008NqmDPSAZ/signing-a-custom-jwt-with-rsa256

Added documentation how to create a Custom-SAML-Assertion

---

content/en/docs/apim_policydev/apigw_polref/integrity_additional.md

As you may know, proper support for JWT is required a lot by our customers and the standard JWT Filters are too limited for day-to-day use-cases. 
With that scripting example we can give them a kind of kick-starter how to create a signed JWT depending on their needs.

Included an example how to create a custom JWT

---

content/en/docs/cass_admin/cassandra_config.md

I also included the sentence, why the system_auth must included. This helps, when customer comes along that problem (User-Auth-Failed) and with that information, he knows what he is missing.

Propose changes according to RDAPI-16664

---

content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md

Added text from @GianSchoeman and reviewed entire deprecated section in RN
fixes #338

Deprecate back-end API export

---

content/en/docs/apim_administration/apigtw_admin/admin_non_root.md
content/en/docs/apim_administration/apigtw_admin/manage_operations.md
content/en/docs/apim_administration/apigtw_admin/managetopology.md
content/en/docs/apim_administration/apigtw_admin/trblshoot_get_help.md
content/en/docs/apim_installation/apigtw_install/install_service_packs.md
content/en/docs/apim_installation/apigw_containers/container_patch_sp.md
content/en/docs/apim_installation/apigw_upgrade/upgrade_overview.md
content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
content/en/docs/apim_installation/apiportal_docker/Upgrade_docker.md
content/en/docs/apim_installation/apiportal_install/install_service_pack.md
content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
content/en/docs/apim_relnotes/20200130_apimgr_relnotes/fixed_issues.md
content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
content/en/docs/apimgmt_security/c_secgd_bp_intro.md

- Change or add "update" terminology so it's clear that 7.7.20200130 is an update and not a service pack
- Change all mentions of service pack use "apply" instead of "install" for consistency.
- Remove any specific mentions of this "update" version from generic docs. The update version should only be mentioned in RN. Similarly specific SP version should only be mentioned in the SP readme.
fixes #336

Revise update terminology

---

content/en/docs/apim_installation/apigw_containers/container_patch_sp.md

SP/patch application instructions should mention that the release notes always need to be consulted because they may contain special instructions specific to that release.

Mention release notes in container_patch_sp.md

---

content/en/docs/apim_administration/apigtw_admin/admin_waf.md

Documenting how to Dry-Run Rules before really activating them to avoid False-Positives in a production environment.

Mod security change action

---

content/en/docs/apim_installation/apigtw_install/system_requirements.md

Copied the requirements from 7.6.2 - assuming they have not changed  https://docs.axway.com/bundle/APIGateway_762_InstallationGuide_allOS_en_HTML5/page/Content/InstallGuideTopics/system_requirements.htm

APIG install section “system_requirements” missing for Linux

---

.github/workflows/size-label.yml

@alexearnshaw I think that this [Assign size label](https://github.com/marketplace/actions/assign-size-label) action is what we're looking for.  What I liked about it is that it uses the same labels as the [Kubernetes](https://github.com/kubernetes/kubernetes/labels?q=size) project.
Following the '**Usage**' instructions, I simply created this `.github/workflows/size-label.yml` file with the recommended code. 
In '**Configuration**' I don't know what this env variable mean. I'm not sure if this is something that we must have in the project or if it's something optional, and when we merge this new file to our project, it will automatically label the new PRs.

Add size-label to the tickets

---

.github/workflows/conflict-label.yml

@alexearnshaw I've found this [Auto-label merge conflicts](https://github.com/marketplace/actions/auto-label-merge-conflicts) GitHub action, which is also helpful. Sometimes is not easy to see that there's a conflict, but with the issue being automatically labeled, it will be easier to see.
The only think I've changed from the original example file is that they add the label **on push**, and I've set ours to **on pull**. So I'm not sure if this is going to work :)

Add conflict-label to the tickets

---

content/en/docs/apim_installation/apiportal_docker/docker_troubleshoot.md

The location of the server key & certificate was wrong. From:
```
/etc/httpd/server.key
/etc/httpd/server.crt
```
to:
```
/etc/httpd/conf/server.key
/etc/httpd/conf/server.crt
```
I double checked it in the mentioned script: `/tmp/genssl.sh`:
```
KEY=$APACHE_ROOT/conf/server.key
CRT=$APACHE_ROOT/conf/server.crt
LOCK=$APACHE_ROOT/conf/server.key.lock
```

Location of the server key and certificate fixed

---

static/admin/config.js

Complements #513 
@alexearnshaw PR 513 didn't work, I think because I should've added 'central' before 'Catalog'

Add Unified Catalog to CMS

---

.github/workflows/ciworkflow.yml

Context: https://github.com/Axway/axway-open-docs/pull/696#issuecomment-624269827

Specify version of markdownlint-cli for CI to avoid unexpected breaks.

---

content/en/docs/shared_services/supportapi/formats/add_note_res.md
content/en/docs/shared_services/supportapi/formats/close_case_res.md
content/en/docs/shared_services/supportapi/formats/create_case_req.md
content/en/docs/shared_services/supportapi/formats/create_case_res.md
content/en/docs/shared_services/supportapi/formats/error_response.md
content/en/docs/shared_services/supportapi/formats/get_case_res.md
content/en/docs/shared_services/supportapi/formats/list_cases_req.md
content/en/docs/shared_services/supportapi/formats/list_cases_res.md
content/en/docs/shared_services/supportapi/methods/add_note.md
content/en/docs/shared_services/supportapi/methods/close_case.md
content/en/docs/shared_services/supportapi/methods/create_case.md
content/en/docs/shared_services/supportapi/methods/download_attachment.md
content/en/docs/shared_services/supportapi/methods/get_accounts.md
content/en/docs/shared_services/supportapi/methods/get_case.md
content/en/docs/shared_services/supportapi/methods/get_products.md
content/en/docs/shared_services/supportapi/methods/list_cases.md

Absolute paths(ex. /a/b/c) are now used instead of directory traversal(ex. ../b/c) ones
Fixed broken URIs that used double hyphens instead of single ones(ex. #add-note---simple is now #add-note-simple)

[SPHERE-1046] Fix broken links in SphereAPI(Support API) docs

---

content/en/docs/apim_administration/apimgr_admin/api_mgmt_promote.md

Updating the api_mgmt_promote to document new properties added to the apimanager-promote script:
- application.apis.remove.all  added by https://jira.axway.com/browse/RDAPI-20218.
- organization.apis.remove.all added by https://jira.axway.com/browse/RDAPI-20829
https://deploy-preview-1419--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_promote/

RDAPI-20218 Add two new properties to promotion.properties file

---

content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md

https://deploy-preview-1582--axway-open-docs.netlify.app/docs/apim_relnotes/20210130_apimgr_relnotes/
Added RDAPI-22573 issue and workaround to Jan21 release notes.

RDAPI-22573 Update Jan21 Known issues

---

content/en/docs/apim_administration/apigtw_admin/manage_user_access.md
content/en/docs/apim_reference/config_files_reference.md
content/en/docs/apimgmt_security/c_secgd_bp_intro.md
content/en/docs/apimgmt_security/c_secgd_config_secconfig.md

We now have the ability to set a passphrase policy for nodemanagers and groups. This is similar to how the current password policy works but we cannot edit the passphrase policy through the UI like the password policy. We can edit it through an API call which is recommended or manually.
https://deploy-preview-1639--axway-open-docs.netlify.app/docs/apim_administration/apigtw_admin/manage_user_access/
https://deploy-preview-1639--axway-open-docs.netlify.app/docs/apim_reference/config_files_reference/
https://deploy-preview-1639--axway-open-docs.netlify.app/docs/apimgmt_security/c_secgd_bp_intro/
https://deploy-preview-1639--axway-open-docs.netlify.app/docs/apimgmt_security/c_secgd_config_secconfig/
_Although Netlify will add this …

RDAPI-22806 Documentation for Passphrase Password Policy

---

content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md

Description
Adding a note to the 'Configure API Manager request rate limiter' section to warn customers who have a large number of entities to consider increasing the default values for this security feature.
Deploy Preview Link
[https://deploy-preview-1694--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_config/#configure-api-manager-request-rate-limiter](https://deploy-preview-1694--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_config/#configure-api-manager-request-rate-limiter)

RDAPI-23550 - Update Configure API Manager request rate limiter

---

content/en/docs/apim_installation/apigtw_install/install_policy_studio.md

Adding a brief note outlining why Policy Studio should not be run as a privileged user, so as to mitigate against potential privilege-escalation vulnerabilities.
https://deploy-preview-1717--axway-open-docs.netlify.app/docs/apim_installation/apigtw_install/install_policy_studio/

[RDAPI-22268] [CWE-378] Insecure Temporary Directory used by Jetty in Policy Studio

---

content/en/docs/cass_admin/cassandra_bur.md

Adding notes to Cassandra backup and restore documentation to outline the need to run KPS Admin Re-encrypt if moving data between environments with different domain ids. This is as a result of the Common Criteria Cipher scheme upgrade
https://deploy-preview-1749--axway-open-docs.netlify.app/docs/cass_admin/cassandra_bur/

 RDAPI- 23632 - Changes to Cassandra Backup and Restore doc as a result of CC Cipher Scheme change

---

content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md

Adding one line to the known issues of the May 2020 release notes. 
RDAPI-23063 ticket found that May 2020 can open Policy Studio projects from future releases so we had to add it as a known issue.
https://deploy-preview-1756--axway-open-docs.netlify.app/docs/apim_relnotes/20200530_apimgr_relnotes/#known-issues

[RDAPI-23063] Adding to May2020 release note for PS future releases bug

---

content/en/docs/apim_installation/apigtw_install/metrics_db_install.md

https://deploy-preview-1784--axway-open-docs.netlify.app/docs/apim_installation/apigtw_install/metrics_db_install/#connect-to-a-database-url
There's no Jira ticket associated. This is to update '**Connect to a database URL**' to add information on how to to secure communication between clients (API-GW and Node-Manager) and a metrics database server (in this case AWS RDS MySQL), since it took me hours to find the solution on how to configure TLS for a Metrics database connection. As this was not mentioned in our docs and within Policy Studio one cannot configure transport security for database connections.
This is to address customer requirement/ feedback to a security audit.

Update Connect to a database URL section with Example Setup for TLS with MySQL Server

---

content/en/docs/apim_policydev/apigw_polref/utility_additional.md

https://deploy-preview-1961--axway-open-docs.netlify.app/docs/apim_policydev/apigw_polref/utility_additional/
I updated the section on the Execute External Process filter to mention exec.output and exec.error which are the variables that capture the output of the process you execute.  
I also mentioned why the "expected error code" is important--it determines when the filter succeeds or fails--and mentioned that the default of zero assumes you're following the old Unix convention where processes return zero on success and non-zero on failure.  Previously it told you that the value defaulted to zero, but gave no indication of why you would change it or what effect that would have.  The filter logic is such that it succeeds when you get whatever you have configured as the expected return …

Update section on Execute External Process

---

content/en/docs/apim_administration/apigtw_admin/admin_redactors.md

Some customers have been confused about the instructions to add the line enabling redaction "at the end of the file". See for example case 01236111. I've added a note to indicate that it's important to get this right.
https://deploy-preview-1982--axway-open-docs.netlify.app/docs/apim_administration/apigtw_admin/admin_redactors/

Add note to ensure customers add "redaction.xml" correctly

---

content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md

https://deploy-preview-2008--axway-open-docs.netlify.app/docs/apim_administration/apimgr_sso/c_saml_trouble/#enable-traces-for-sso
Updated to reflect what to change the log level to. 
Updated the configuration file sample to reflect the target state, not the default state.
Added reminder to set the trace level back to the default
_Put an x in the boxes that apply. This is simply a …

Update Enable traces for SSO - change Level from Erro to Debut

---

content/en/docs/central/cli_central/_index.md
content/en/docs/central/cli_central/cli_install.md
content/en/docs/central/mesh_management/using_redhat_openshift.md

* Bumped Node.js version to 12.13.0 ([APIGOV-19756](https://jira.axway.com/browse/APIGOV-19756))
* Replaced Amplify CLI references with Axway CLI ([APIGOV-19763](https://jira.axway.com/browse/APIGOV-19763))
* Updated expected output with latest Axway CLI output ([APIGOV-20171](https://jira.axway.com/browse/APIGOV-20171))

Central CLI doc updates:

---

content/en/docs/apim_reference/system_props.md

Introduce the following 3 flags for RDAPI-24851:
com.axway.apigw.dbconnection.removeabandoned
com.axway.apigw.dbconnection.removeabandoned.timeoutms
com.axway.apigw.dbconnection.testonreturn
and the following 2 flags for RDAPI-25249:
com.axway.api.runtime.broker.parameters.skipRequiredValidation
com.axway.api.runtime.broker.parameters.skipEnumValidation
https://deploy-preview-2094--axway-open-docs.netlify.app/docs/apim_reference/system_props/

[RDAPI-24851] [RDAPI-25249] Introduce new flags

---

content/en/docs/cass_admin/cassandra_troubleshooting.md

If Cassandra keyspace restored is not visible via API Manager
https://deploy-preview-2228--axway-open-docs.netlify.app/docs/cass_admin/cassandra_troubleshooting/#restored-keyspace-not-visible-in-api-manager-ui

RDAPI-26661  adding keyspace restore note

---

content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md

https://deploy-preview-2327--axway-open-docs.netlify.app/docs/apim_relnotes/20220530_apimgr_relnotes/#list-of-allowed-http-methods-for-api-gateway-cors-request

RDAPI-26585 Add section for changes in a list of allowed HTTP methods for API Gateway CORS request
